# Generated by Django 2.1.5 on 2019-03-21 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseliquor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseliquor',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='baseliquor',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='baseliquor',
            old_name='location',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='baseliquor',
            old_name='photo',
            new_name='pic',
        ),
        migrations.RemoveField(
            model_name='baseliquor',
            name='created_at',
        ),
        migrations.AddField(
            model_name='baseliquor',
            name='material',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
